name: Node.js CI

on:
  schedule:
    - cron: "0 */2 * * *" # This runs the workflow every 2 hours
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install 
      working-directory: ./src

    - name: Install dotenv
      run: npm install dotenv
      working-directory: ./src

    - name: Check for lock file
      run: |
          if [ -f /src/bot.lock ]; then
            echo "Another instance is running. Exiting."
            exit 0
          fi
          touch /src/bot.lock

    - name: Create .env file
      run: echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} > .env
      working-directory: ./src
      
    - name: Run the bot
      run: node index.js
      working-directory: ./src

    - name: Cleanup
      if: always()
      run: rm -f /src/bot.lock
