name: Node.js CI

on:
  schedule:
    - cron: "0 */6 * * *" # This runs the workflow every 6 hours
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install 
      working-directory: ./src

    - name: Install dotenv
      run: npm install dotenv
      working-directory: ./src


    - name: Create .env file
      run: echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} > .env
      working-directory: ./src
      
    - name: run the bot
      run: node index.js
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      working-directory: ./src
